// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmuoc_612uOf1HZcwUKFbeclwYdJKY08',
    appId: '1:170107962344:web:af4c44475d7d6c05209a5d',
    messagingSenderId: '170107962344',
    projectId: 'rava-fc1eb',
    authDomain: 'rava-fc1eb.firebaseapp.com',
    storageBucket: 'rava-fc1eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_aqqjC-dQJDWm4I4kfV9wsHZT05euOlQ',
    appId: '1:170107962344:android:6b9dc39b6b370f9d209a5d',
    messagingSenderId: '170107962344',
    projectId: 'rava-fc1eb',
    storageBucket: 'rava-fc1eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3wxegvgUwiQhMF0Y4UCNOdeV2Zgb7kg',
    appId: '1:170107962344:ios:45dae6a344b153e9209a5d',
    messagingSenderId: '170107962344',
    projectId: 'rava-fc1eb',
    storageBucket: 'rava-fc1eb.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3wxegvgUwiQhMF0Y4UCNOdeV2Zgb7kg',
    appId: '1:170107962344:ios:45dae6a344b153e9209a5d',
    messagingSenderId: '170107962344',
    projectId: 'rava-fc1eb',
    storageBucket: 'rava-fc1eb.firebasestorage.app',
    iosBundleId: 'com.example.marketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNmuoc_612uOf1HZcwUKFbeclwYdJKY08',
    appId: '1:170107962344:web:3242be0faf311977209a5d',
    messagingSenderId: '170107962344',
    projectId: 'rava-fc1eb',
    authDomain: 'rava-fc1eb.firebaseapp.com',
    storageBucket: 'rava-fc1eb.firebasestorage.app',
  );
}
